# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job_application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=150)),
                ('last_date', models.CharField(max_length=150)),
                ('offered_by', models.CharField(max_length=150)),
            ],
        ),
    ]
