# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_application',
            name='details',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
