# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-03 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0002_job_application_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_application',
            name='url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
