# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typei', models.CharField(max_length=140)),
                ('category', models.CharField(max_length=140)),
                ('opening_date', models.CharField(max_length=140)),
                ('closing_date', models.CharField(max_length=140)),
                ('details', models.TextField()),
            ],
        ),
    ]
