# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-03 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
