# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-07 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_by', models.CharField(max_length=150)),
                ('qualifications', models.CharField(max_length=150)),
                ('catagory', models.CharField(max_length=150)),
                ('details', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
