# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-08 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='temp',
            field=models.URLField(default='https://www.google.com'),
            preserve_default=False,
        ),
    ]
